name: Control Dockerfiles

on:
  push:
    paths:
      - '**'
      - '!README.md'
      - '!LICENSE'
  pull_request:
    branches:
      - 'main'
    paths:
      - '**'
      - '!README.md'
      - '!LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["armv7hf", "aarch64"]
    env:
      exrepo: build-test
      exname: docker-acap
    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ env.example }} application
        env:
          exampletag: "${{ env.exrepo }}_${{ env.exname }}"
        run: ./build.sh ${{ matrix.arch }} $exampletag
